

/* This file contains the PRU instructions in a C array which are to  */
/* be downloaded from the host CPU to the PRU instruction memory.     */
/* This file is generated by the PRU assembler.                       */



const unsigned int PRU0_Code[] =  
{
    0x24000aea,
    0x2300089e,
    0x2300129e,
    0x23000d9e,
    0x2300129e,
    0x0501eaea,
    0x6f00eafb,
    0x2a000000,
    0x240027e2,
    0x2401e2c3,
    0x24601883,
    0xe1002382,
    0x209e0000,
    0x240027e2,
    0x2401e2c3,
    0x24601c83,
    0xe1002382,
    0x209e0000,
    0x240365c0,
    0x24c04080,
    0x0501e0e0,
    0x6f00e0ff,
    0x209e0000
};

